import { Dimensions, StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#79badd',
  },
  first_pane: {
    //marginTop: 67,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 2,
    backgroundColor: '#ffffff',
  },
  pane: {
    width: '100%',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 2,
    backgroundColor: '#ffffff',
    borderColor: '#000000',
  },
  toggle_button_container: {
    position: 'absolute',
    bottom: 15,
    right: 15,
    zIndex: 10,
  },
  big_font: {
    width: '100%',
    fontSize: 32,
    padding: 9,
    textAlign: 'center',
    fontFamily: 'Raleway_400Regular',
  },
  middle_font: {
    width: '100%',
    fontSize: 20,
    paddingHorizontal: 10,
    fontFamily: 'NunitoSans_300Light',
  },
  small_font: {
    width: '100%',
    fontSize: 20,
    paddingHorizontal: 10,
    fontFamily: 'NunitoSans_300Light',
  },
  list: {
    width: '100%',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 2,
    backgroundColor: '#eeeeee',
  },
  search_pane: {
    borderColor: '#000000',
    width: '93%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'between',
     height: 40,
     borderRadius: 10,
     padding: 0,
     margin: 5,
     fontSize: 16
  },
  search_field: {
    width: '100%',
    height: 40,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#333333',
    padding: 10,
    margin: 10,
    fontSize: 17,
  },
  button_field: {
    width: '100%',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#333333',
    padding: 7,
    backgroundColor: '#79badd',
  },
  circular_button: {
    width: 60,
    height: 60,
    borderRadius: 30 ,
    borderWidth: 2,
    alignContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-end',
    borderColor: '#333333',
    justifyContent: 'center',
    backgroundColor: '#79badd',
  },
  map: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
    zIndex: 0
  },
screen: {
  flex: 1,
  position: 'relative',
  backgroundColor: '#ffffff',
},
});

export default styles;